CREATE TABLE ads
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    description      TEXT,
    price_per_month  DOUBLE PRECISION,
    max_colocataires INTEGER,
    ville            VARCHAR(255),
    published        BOOLEAN,
    owner_id         BIGINT,
    property_id      BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_ads PRIMARY KEY (id)
);

CREATE TABLE photos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(255),
    caption      VARCHAR(255),
    sort_order   INTEGER,
    content_type VARCHAR(50),
    ad_id        BIGINT,
    CONSTRAINT pk_photos PRIMARY KEY (id)
);

CREATE TABLE properties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address     VARCHAR(255),
    city        VARCHAR(255),
    postal_code VARCHAR(255),
    surface     DOUBLE PRECISION,
    rooms_count INTEGER,
    has_wifi    BOOLEAN,
    has_parking BOOLEAN,
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

CREATE TABLE rooms
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label        VARCHAR(255),
    area         DOUBLE PRECISION,
    is_available BOOLEAN,
    capacity     INTEGER,
    property_id  BIGINT,
    CONSTRAINT pk_rooms PRIMARY KEY (id)
);

ALTER TABLE ads
    ADD CONSTRAINT FK_ADS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);

ALTER TABLE photos
    ADD CONSTRAINT FK_PHOTOS_ON_AD FOREIGN KEY (ad_id) REFERENCES ads (id);

ALTER TABLE rooms
    ADD CONSTRAINT FK_ROOMS_ON_PROPERTY FOREIGN KEY (property_id) REFERENCES properties (id);