CREATE TABLE preferences
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    min_budget        DOUBLE PRECISION,
    max_budget        DOUBLE PRECISION,
    location_preferee VARCHAR(255),
    genre_coloc       VARCHAR(255),
    apartment_type    VARCHAR(255),
    pets_allowed      BOOLEAN,
    CONSTRAINT pk_preferences PRIMARY KEY (id)
);

CREATE TABLE profiles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    prenom      VARCHAR(255),
    nom         VARCHAR(255),
    age         INTEGER,
    ville       VARCHAR(255),
    telephone   VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE proprietaire_properties
(
    proprietaire_id BIGINT NOT NULL,
    property_id     BIGINT
);

CREATE TABLE reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating         INTEGER                                 NOT NULL,
    comment        VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    locataire_id   BIGINT,
    target_user_id BIGINT,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE role
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type     VARCHAR(20),
    email         VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    nom           VARCHAR(50)                             NOT NULL,
    prenom        VARCHAR(50)                             NOT NULL,
    telephone     VARCHAR(255),
    age           INTEGER,
    ville         VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    budget        DOUBLE PRECISION,
    villepreferee VARCHAR(255),
    preference_id BIGINT,
    verified      BOOLEAN,
    profile_id    BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE role
    ADD CONSTRAINT uc_role_nom UNIQUE (nom);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_preference UNIQUE (preference_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_profile UNIQUE (profile_id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_LOCATAIRE FOREIGN KEY (locataire_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PREFERENCE FOREIGN KEY (preference_id) REFERENCES preferences (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES profiles (id);

ALTER TABLE proprietaire_properties
    ADD CONSTRAINT fk_proprietaire_properties_on_proprietaire FOREIGN KEY (proprietaire_id) REFERENCES users (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);