spring.application.name=config-service

server.port=8888

# Management endpoints
management.endpoints.web.exposure.include=health,info,env,refresh

spring.cloud.config.server.git.uri=https://github.com/HaitamBny/config-server.git
spring.cloud.config.server.default-label=main
spring.cloud.config.server.git.refresh-rate=60
spring.cloud.config.server.git.clone-on-start=true
